repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: trailing-whitespace
-   repo: https://github.com/KevinChris7/testing-repo
    rev: cf80edb
    hooks:
    -   id: trailing-whitespace