#!/usr/bin/env groovy

node(){
    def work_dir = 'project/internaltools'
    def output
    stage("Git Checkout"){
        checkout(
            [
                $class: 'GitSCM',
                branches: [[name: 'master']],
                userRemoteConfigs: [[url: "${GIT_REPO_NOTIFY}", credentialsId: "${CREDENTIALS_ID}"]]
            ]
        )
        println("Checkout Completed Succesfully")
    }
    stage("Install GIT&Pre-commit") {
        try{
            sh('''
                #!/bin/bash
                mkdir -p ${JENKINS_HOME}/project
                mkdir -p ${JENKINS_HOME}/project/internaltools
                git --version $?
                if [ $? -eq 0 ]; then
                    echo "GIT is already installed"
                else 
                    sudo yum install git -y
                    echo "Installed GIT"
                fi
                if hash pre-commit 2>/dev/null; then
                    echo "pre-commit exists"
                else
                    echo "Installing Pre-Commit...."
                    pip install pre-commit
                    echo "Pre-Commit Installed successfully"                
                    echo "$PWD"
                fi
            ''')
        }
        catch(e){
            println("Exception occurred in Installing GIT and Pre-Commit")
        }
    }

        // finally {
        //     deleteDir()
        // }
}